#!/bin/bash
# Reference: https://github.com/MISP/misp-docker

# Exit immediately if a command exits with a non-zero status
set -e

source "./libs/main.sh"
define_env
define_paths
source "./libs/install-helper.sh"
pre_install "misp"

replace_envs "${workdir}/${service_name}/.env"
source .env

# Step 2: Start the service
printf "Starting the service...\n"
docker compose up -d --force-recreate
printf "Starting the Sllep...\n"
sleep 70
printf "Ending the Sllep...\n"

NEWUSERNAME_PASSWORD="$(
  {
    tr -dc 'A-Z' </dev/urandom | head -c1
    tr -dc 'a-z' </dev/urandom | head -c1
    tr -dc '0-9' </dev/urandom | head -c1
    tr -dc 'A-Za-z0-9' </dev/urandom | head -c12
  } | fold -w1 | shuf | tr -d '\n'
  echo
)"
ADMINE_PASSWORD="$(
  {
    tr -dc 'A-Z' </dev/urandom | head -c1
    tr -dc 'a-z' </dev/urandom | head -c1
    tr -dc '0-9' </dev/urandom | head -c1
    tr -dc 'A-Za-z0-9' </dev/urandom | head -c12
  } | fold -w1 | shuf | tr -d '\n'
  echo
)"

docker exec -it misp-misp-core-1 /var/www/MISP/app/Console/cake user list
printf "user list end\n"

docker exec -it misp-misp-core-1 /var/www/MISP/app/Console/cake user create "${READ_ONLY_USER}" 6 1 "Aa1234567890"
sleep 5
docker exec -it misp-misp-core-1 /var/www/MISP/app/Console/cake user list
printf "user list end\n"

sleep 2
docker exec -it misp-misp-core-1 /var/www/MISP/app/Console/cake user change_pw --no_password_change 2 "$NEWUSERNAME_PASSWORD"
sleep 2
docker exec -it misp-misp-core-1 /var/www/MISP/app/Console/cake user change_pw --no_password_change 1 "$ADMINE_PASSWORD"
sleep 2
docker exec -it misp-misp-core-1 /var/www/MISP/app/Console/cake user list
docker exec -it misp-misp-core-1 /var/www/MISP/app/Console/cake admin setSetting Security.password_policy_length 8
docker exec -it misp-misp-core-1 /var/www/MISP/app/Console/cake admin setSetting MISP.default_publish_alert false  
docker exec -it misp-misp-core-1 /var/www/MISP/app/Console/cake admin setSetting MISP.correlation_engine "NoAcl"
docker exec -it misp-misp-core-1 /var/www/MISP/app/Console/cake Server loadDefaultFeeds
sleep 5
ID_ARRAY=($FEEDS_ID)

# Iterate over the array
for id in "${ID_ARRAY[@]}"; do
    echo "Processing ID: $id"
    docker exec -it misp-misp-core-1 /var/www/MISP/app/Console/cake Server toggleFeed "$id"

    # Your logic here
done


echo "############################################"
echo "### READ_ONLY_USER created: ${READ_ONLY_USER}"
echo "### Password: $NEWUSERNAME_PASSWORD"
echo "### User: admin@admin.test"
echo "### Password: $ADMINE_PASSWORD"
echo "############################################"

echo "### Autogenerated by MISP scripts ###" >> "${workdir}/.env"

echo "USER=admin@admin.test" >> "${workdir}/.env"
echo "MISP_PASSWORD=$ADMINE_PASSWORD" >> "${workdir}/.env"
echo "READ_ONLY_USER=$READ_ONLY_USER" >> "${workdir}/.env"
echo "MISP_PASSWORD=$NEWUSERNAME_PASSWORD" >> "${workdir}/.env"


sleep 5
docker restart misp-misp-core-1
print_green_v2 "$service_name deployment started." "Successfully"