services:
  agent:
    image: portainer/agent:${PORTAINER_AGENT_VERSION:-2.21.0}
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    env_file:
      - .env
    networks:
      - net
      - main_network
  portainer:
    image: portainer/portainer-ce:${PORTAINER_VERSION:-2.21.0}
    container_name: portainer
    ports:
      - 9443:9443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - net
      - main_network

networks:
  net:
  main_network:
    external: true
