services:
  nginx:
    container_name: nginx
    image: nginx:${NGINX_VERSION}
    restart: always
    ports:
      - ${NGINX_HTTP_PORT}:80
      - ${NGINX_HTTPS_PORT}:443
      - "8843:9443"
    volumes:
      - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./etc/ssl/certs:/etc/ssl/certs
      - ./etc/ssl/private:/etc/ssl/private
        #  - ./etc/nginx/sites-enabled/example.com:/etc/nginx/sites-enabled/example.com
    networks:
      - net
      - main_network


networks:
  net:
  main_network:
    external: true

