name: risx-mssp

services:
  mysql:
    restart: unless-stopped
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "true"
      MYSQL_DATABASE: "mssp"
    build:
      dockerfile: mysql.Dockerfile
      secrets:
        - &passwd shoresh-passwd
    expose:
      - 3306
      - 33060
    secrets:
      - *passwd
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - net
      - main_network
  backend:
    restart: unless-stopped
    depends_on:
      - mysql
    build:
      dockerfile: backend.Dockerfile
    expose:
      - 5555
    secrets:
      - source: *passwd
        target: env.DATABASE_PASSWORD.secret
      - source: dehashed-u
        target: env.DEHASHED_U.secret
    env_file: environment.sh
    volumes:
      - backend-init-check:/init_check
    networks:
      - net
      - main_network
  frontend:
    restart: unless-stopped
    depends_on:
      - backend
    build:
      dockerfile: frontend.Dockerfile
    expose:
      - 3003
    configs:
      - source: mssp_config.json
        target: /usr/share/nginx/html/mssp_config.json
    networks:
      - net
      - main_network

networks:
  net:
  main_network:
    external: true

configs:
  mssp_config.json:
    file: mssp_config.json

volumes:
  mysql-data:
    name: risx-mssp-mysql-data
  backend-init-check:
    name: risx-mssp-backend-init-check

secrets:
  shoresh-passwd:
    file: shoresh.passwd
  dehashed-u:
    file: env.DEHASHED_U.secret