name: risx-mssp

services:
  mysql:
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: "mssp"
      MYSQL_ROOT_PASSWORD: "/run/secrets/MYSQL_ROOT_PASSWORD"
    expose:
      - 3306
      - 33060
    build:
      dockerfile: mysql.Dockerfile
      no_cache: true
      secrets:
        - SHORESH_PASSWD
    healthcheck:
      test:
        - CMD
        - /bin/sh
        - -c
        - |
          mysql -u shoresh -p$(cat /run/secrets/SHORESH_PASSWD) --batch --execute 'SHOW TABLES;' mssp
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    secrets:
      - SHORESH_PASSWD
      - MYSQL_ROOT_PASSWORD
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - net

  backend:
    container_name: risx-mssp-backend
    restart: unless-stopped
    depends_on:
      mysql:
        condition: service_healthy
        restart: true
    build:
      dockerfile: .Dockerfile
      context: backend
    secrets:
      - source: SHORESH_PASSWD
        target: DATABASE_PASSWORD
      - DEHASHED_U
    env_file: backend/.env
    expose:
      - 5555
    ports:
      - 5555:5555
    volumes:
      - ./backend/init-check:/init_check
      - type: bind
        source: ./backend/mssp-back.log
        target: /app/msspBack.log
    networks:
      - net
      - main_network

  frontend:
    container_name: risx-mssp-frontend
    restart: unless-stopped
    depends_on:
      - backend
    build:
      dockerfile: .Dockerfile
      context: frontend
    env_file: frontend/.env
    ports:
      - 3003:3003
    configs:
      - source: frontend/mssp_config.json
        target: /usr/share/nginx/html/mssp_config.json
    networks:
      - net
      - main_network

networks:
  net: {}
  main_network:
    external: true

configs:
  mssp_config.json:
    file: mssp_config.json

volumes:
  mysql-data:
    name: risx-mssp-mysql-data
  backend-init-check:
    name: risx-mssp-backend-init-check

secrets:
  MYSQL_ROOT_PASSWORD:
    file: env.mysql_root_password.secret
  SHORESH_PASSWD:
    file: shoresh.passwd
  DEHASHED_U:
    file: env.DEHASHED_U.secret
