services:
  cyberchef:
    container_name: cyberchef
    image: ghcr.io/gchq/cyberchef:${CYBERCHEF_IMAGE_TAG:-latest}
    env_file:
      - .env
    networks:
      - main_network
    expose:
      - 80
    restart: unless-stopped

networks:
  main_network:
    external: true
